### ISSUE TITLE
there might be some species

### ISSUE THREAD

**Issue by Max-Lo-007** [zhaotao1987/SynNet-Pipeline#10]

**Comment by Max-Lo-007** [comment]
hello, I think there are some species missing from the [51_Genomes_Blocks] data file, such as chlamydomonas reinhardtii.

**Comment by zhaotao1987** [comment]
Hi Max, that is because there is no synteny detected between Chlamydomonas reinhardtii and any other plant species, due to the large evolutionary distance and genome rearrangements.
