### ISSUE TITLE
SynetBuild-X.sh: line 132: detect_collinear_tandem_arrays: command not found

### ISSUE THREAD

**Issue by alexvasilikop** [zhaotao1987/SynNet-Pipeline#11]
Hi,

Thanks for developing such useful tools,

I am trying to build the synteny network like below but I get this output warning see below.
What might be the reason?
$bash SynetBuild-X.sh 6 3 50 20

..
cCAJNOQ010077972.1.html
dcCAJNOQ010078021.1.html
dcCAJNOQ010078108.1.html
dcCAJNOQ010078245.1.html
Done! [57.500 seconds elapsed]
duplication modes!
Reading BLAST file and pre-processing
Generating BLAST list
94597 matches imported (41496 discarded)
89489 pairwise comparisons
13 alignments generated
Type of dup	Code	Number
Singleton	0	8187
Dispersed	1	37686
Proximal	2	157
Tandem	3	677
WGD or segmental	4	156
Now we detect collinear tandem arrays.
SynetBuild-X.sh: line 132: detect_collinear_tandem_arrays: command not found
610 alignments generated
Type of dup	Code	Number
Singleton	0	5090
Dispersed	1	13960
Proximal	2	5247
Tandem	3	2213
WGD or segmental	4	20078
Now we detect collinear tandem arrays.
SynetBuild-X.sh: line 132: detect_collinear_tandem_arrays: command not found

..

Thanks

**Comment by zhaotao1987** [comment]
`detect_collinear_tandem_arrays `is a script of MCScanX, it's under `/MCScanX/downstream_analyses/`
So make sure it's installed and the path was exported.
btw, depending on your purpose, this step is usually not necessary, it will update the collinearity file, if the anchor genes contain tandem genes nearby.
