### ISSUE TITLE
Error in check_gene_names(seq, annotation) , Sequence names in 'seq' do not match gene names in 'annotation' for:

### ISSUE THREAD

**Issue by jhcuarta** [zhaotao1987/SynNet-Pipeline#13]
Hi
I'm trying to run syntenet but I got stacked using check_input(proteomes, annotation); all my files were taken from prokka 1.14.6, so I dont really nkow why theres discrepancies in the names; could you please guide me through the files preparation I didnt get quite well

> setwd("~/Documents/syntenet") 
> library(syntenet) 
> fasta_dir <- system.file("extdata", "sequences", package = "syntenet") 
> proteomes <- fasta2AAStringSetlist(fasta_dir) > gff_dir <- system.file("extdata", "annotation", package = "syntenet") > annotation <- gff2GRangesList(gff_dir) 
> check_input(proteomes, annotation) Error in check_gene_names(seq, annotation) :    Sequence names in 'seq' do not match gene names in 'annotation' for: 
1. 10432_62_LANL 2. 107V1216_BRAC 3. 1154_74_LANL 4. 11S_UM 5. 1346_SC 6. 1362_SC 7. 146N_ILS 8. 146P_ILS 9. 1587_BI 10. 1627_SC 11. 17609_UM 12. 1Mo_UM 13. 20000_RIPC 14. 2009V_1135_CDC 15. 2010EL_1786_CDCP 16. 2011EL_1271_48x_CDC 17. 2011EL_1271_97x_CDC 18. 2012EL_1094_CDC 19. 2012EL_1096_CDC 20. 2012EL_1097_60x_CDC 21. 2012EL_1097_89x_CDC 22. 2012EL_1759_CDC 23. 2012EL_1760_CDC 24. 2012EL_1765_CDC 25. 2012EL_1776_CDC 26. 2012Env_9_UF 27. 2015V_1118_126x_CDC 28. 2015V_1118_56x_CDC 29. 2018HL24_CCDCP 30. 20390_UM 31. 20478_UM 32. 21B_UM 33. 220075_6_UM 34. 220076_6_UM 35. 22043200_C1_UM 36. 22043202_C1_UM 37. 22043204_C1_UM 38. 22044108_C3_UM 39. 22087102_C2_UM 40. 22087500_C9_UM 41. 2740_80_BI 42. 2740_80_IU 43. 2Mo_UM 44. 31Ki_UM 45. 330033_C1_UM 46. 330073_A_UM 47. 330073_B_UM 48. 330081_UM 49. 330110_UM 50. 330113_UM 51. 330440_C1_UM 52. 330898_C2_UM 53. 330920_A_UM 54. 330920_B_UM 55. 3528_08_CDC 56. 35
--
I try to erase those failing files, but when I rerun the script mores sequences show

**Comment by zhaotao1987** [comment]
Sorry for the late reply. 
Please post synetnet R package related questions on https://github.com/almeidasilvaf/syntenet/issues
