### ISSUE TITLE
SynetBuilding-  Diamond.sh

### ISSUE THREAD

**Issue by SAMANDOLL** [zhaotao1987/SynNet-Pipeline#3]
According to your instruction;
Put all pairs of "*.pep" and "*.bed" of your genomes under one folder, copy the script (SynetBuilding-  Diamond.sh) to the same folder.
after making dir ; mkdir ../DiamondGenomesDB
diamond makedb --in ../$i.pep -d ../DiamondGenomesDB/$i

Error
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.
#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: ../.pep
Opening the database file... No such file or directory
 [8.7e-05s]
Error: Error opening file ../.pep**

**Comment by zhaotao1987** [comment]
Maybe check your input genome abbreviations at Line 41 of the script. 

> According to your instruction;
> Put all pairs of "_.pep" and "_.bed" of your genomes under one folder, copy the script (SynetBuilding- Diamond.sh) to the same folder.
> after making dir ; mkdir ../DiamondGenomesDB
> diamond makedb --in ../$i.pep -d ../DiamondGenomesDB/$i
> 
> Error
> diamond v0.9.24.125 | by Benjamin Buchfink [buchfink@gmail.com](mailto:buchfink@gmail.com)
> Licensed under the GNU GPL https://www.gnu.org/licenses/gpl.txt
> Check [http://github.com/bbuchfink/diamond](https://github.com/bbuchfink/diamond) for updates.
> #CPU threads: 4
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Database file: ../.pep
> Opening the database file... No such file or directory
> [8.7e-05s]
> Error: Error opening file ../.pep**
