### ISSUE TITLE
how to use the results performed  by SynetBuild-X.sh? 

### ISSUE THREAD

**Issue by weifei888** [zhaotao1987/SynNet-Pipeline#4]
I performed the shell script SynetBuild-X.sh, finally I got the result looks like:

at0-0b    150.0     at__AT1G48590 at__AT3G17980
at0-1b    150.0     at__AT1G48598 at__AT3G17998
at0-2b    150.0     at__AT1G48600 at__AT3G18000
at1-0b    150.0     at__AT4G25660 at__AT4G25680
at1-1b    150.0     at__AT4G25670 at__AT4G25690
       
Is the “0-0b” “0-1b” “0-2b” in the first column means the “cluster” in the paper?
And if I set the 1st column as “interaction type”, 2nd column as “source node attribute”, 3rd column as “source node”, 4th  column as “target node” in the cytoscape, the result would be right?

**Comment by zhaotao1987** [comment]
@weifei888  The columns are "blockID", "block_score", "source", and "target", the last two columns are the key columns for visualizing networks in cytoscape.
