### ISSUE TITLE
Minor fix suggestions for infomap.r and Phylogenomic_Profiling.r

### ISSUE THREAD

**Issue by FatihSarigol** [zhaotao1987/SynNet-Pipeline#7]
Hello, thank you for the SynNet pipeline!

As also follows from the wiki description, and as also commented in the R script, the input file for `infomap.r` should be tab separated:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/infomap.r#L4

But the code says different:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/infomap.r#L15

The error message is not informative, so it wasn't straightforward to spot this. When I replaced tabs with spaces in my input file it worked.

Also, in `Phylogenomic_Profiling.r` this way of calling the command variable doesn't seem to work, and again gives an uninformative error; at least for two versions of R that I tried it with in Unix `3.6.1` and `4.0.3` both errored out about the command that contains also this line:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/Phylogenomic_Profiling.r#L72

As a solution, I uncommented this line:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/Phylogenomic_Profiling.r#L64

and changed it into this:

`pdf("PhylogenomicProfile.pdf",width=8,height=8,onefile=FALSE)`

and commented this line:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/Phylogenomic_Profiling.r#L72

and uncommented this:

https://github.com/zhaotao1987/SynNet-Pipeline/blob/1665f0327decea8ec6a8fd3810b1521f94e62a45/Phylogenomic_Profiling.r#L75

And here is a small suggestion, adding this [BinaryDataandTranspose.r](https://github.com/zhaotao1987/Syn-MRL/blob/084c7de2b1d11c09fece5f7d5821778db030c035/BinaryDataandTranspose.r
) into SynNet build.

**Comment by zhaotao1987** [comment]
@FatihSarigol  Thanks a lot for the suggestions, indeed ;) I will adopt these.
