### ISSUE TITLE
Getting a size error when carrying out Phylogenetic profiling 

### ISSUE THREAD

**Issue by Dearbhaile** [zhaotao1987/SynNet-Pipeline#8]
Hi Dr.Zhao,

I have run into an error when I am carrying out the Phylogenetic profiling of the pipeline. I am using 94 ecdyzosoan genomes and am getting this error:

**Loading required package: permute
Loading required package: lattice
This is vegan 2.5-7
Error in hclust(d, method = "ward.D") :
size cannot be NA nor exceed 65536
Execution halted**

Could you help me overcome this?

All the best,
Dearbhaile.

**Comment by zhaotao1987** [comment]
Solved? Very sorry for the late reply.. @Dearbhaile  Maybe the data matrix is too big, Sometimes transpose the matrix may help in clustering. Or you filter the matrix by some criterion before clustering.
