### ISSUE TITLE
My branches are very long

### ISSUE THREAD

**Issue by Dearbhaile** [zhaotao1987/SynNet-Pipeline#9]
Hi Zhao, 

I am writing to ask you on some issue with results. I am using the pipeline with Ecdysozoa genomes of which some have some notoriously long branches. I have attempted many different parameters and increased the number of genomes <50 genomes and I am getting a tree result with just crazily long branches and odd placements. My intuition is that some of the genomes have very few genes as markers and others have more which is causing this skew but I was wondering if you have any advice on how to improve this issue and get cleaner results like you achieved in your angiosperm paper.

**Comment by zhaotao1987** [comment]
Dear Dearbhaile,

Very long branches usually indicate that there are many specific synteny clusters shared for the taxons on that branch. I think first use highly quality genomes, if some genomes are highly fragmented and poorly annotated, containing many TE related replicated proteins (can bring intra-genome blocks). This may affect synteny detection. So check the initial synteny blocks also helps, to see whether the blocks are all of high quality, if something weird exists.

**Comment by zhaotao1987** [comment]
Dear Dearbhaile,

Very long branches usually indicate that there are many specific synteny clusters shared for the taxons on that branch. I think first use highly quality genomes, if some genomes are highly fragmented and poorly annotated, containing many TE related replicated proteins (can bring intra-genome blocks). This may affect synteny detection. So check the initial synteny blocks also helps, to see whether the blocks are all of high quality, if something weird exists.
